import {
  faArrowLeft,
  faArrowRight,
  faBars,
  faBasketShopping,
  faBookOpen,
  faCalendarCircleExclamation,
  faCircleHalfStroke,
  faDesktop,
  faMessages,
  faMoon,
  faPalette,
  faPaperPlane,
  faPenClip,
  faPlay,
  faRightFromBracket,
  faRightToBracket,
  faSquarePhoneFlip,
  faSunBright,
} from '@fortawesome/pro-solid-svg-icons'
import {
  faFacebook,
  faInstagram,
  faLinkedin,
  faPinterest,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons'

export const fontAwesomeIconDefinitions = {
  solid: {
    'arrow-left': faArrowLeft,
    'arrow-right': faArrowRight,
    bars: faBars,
    'basket-shopping': faBasketShopping,
    'book-open': faBookOpen,
    'calendar-circle-exclamation': faCalendarCircleExclamation,
    'circle-half-stroke': faCircleHalfStroke,
    desktop: faDesktop,
    messages: faMessages,
    moon: faMoon,
    palette: faPalette,
    'paper-plane': faPaperPlane,
    'pen-clip': faPenClip,
    play: faPlay,
    'right-from-bracket': faRightFromBracket,
    'right-to-bracket': faRightToBracket,
    'square-phone-flip': faSquarePhoneFlip,
    'sun-bright': faSunBright,
  },
  brands: {
    facebook: faFacebook,
    instagram: faInstagram,
    linkedin: faLinkedin,
    pinterest: faPinterest,
    youtube: faYoutube,
  },
}
